app = 'homesherut-db'
primary_region = 'ams'

[build]
  image = 'mysql:8.0'

[env]
  MYSQL_DATABASE = 'railway'

[[mounts]]
  source = 'mysql_data'
  destination = '/var/lib/mysql'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
